services:
  - type: web
    name: mockapi-backend
    env: python
    region: oregon
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1
